ARG KNK_REGISTRY_URL=ghcr.io/inverse-inc/packetfence
ARG IMAGE_TAG=devel
ARG PROXYSQL_VERSION=3.0.5
ARG PROXYSQL_BRANCH=v3.0.5-systemd
ARG from=${KNK_REGISTRY_URL}/pfbuild-debian-bookworm:${IMAGE_TAG}

FROM ${from} AS build

ARG PROXYSQL_VERSION
ARG PROXYSQL_BRANCH
ENV MAKE=make
ENV MAKEOPT="-j 1"
ENV CURVER=${PROXYSQL_VERSION}
ENV PKG_RELEASE=debian12
ENV PROXYSQL_BUILD_TYPE=clickhouse
ENV BLD_NAME=proxysql
ENV CC=cc
ENV CXX=g++

ARG DEBIAN_FRONTEND=noninteractive

# Install build dependencies

RUN apt-get update && apt-get install -y \
        automake \
        bison \
        bzip2 \
        cmake \
        equivs \
        flex \
        g++ \
        gawk \
        gcc \
        gdb \
        gdbserver \
        git \
        libevent-dev \
        libgnutls28-dev \
        libicu-dev \
        libmariadb-dev \
        libncurses-dev \
        libssl-dev \
        libsystemd-dev \
        libtirpc-dev \
        libtool \
        libunwind-dev \
        libunwind8 \
        make \
        openssl \
        python3 \
        systemd \
        uuid-dev \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/

#
#  Create build directory
#
RUN mkdir -p /opt
WORKDIR /opt

#
# Shallow clone the pxc_scheduler_handler source
#

ARG source_pxc=https://github.com/fdurand/pxc_scheduler_handler.git
ARG COMMIT_ID_PXC=1ee986f38e48607d1f5ed51242ebbf8fb3ec5e2e
RUN git clone -qq ${source_pxc}
WORKDIR pxc_scheduler_handler
RUN git checkout $COMMIT_ID_PXC
RUN go build

#
#  Shallow clone the proxysql source
#
ARG source=https://github.com/inverse-inc/proxysql.git

WORKDIR /opt

RUN mkdir -p /root/ctl
RUN git clone -qq ${source}
WORKDIR proxysql
RUN git checkout ${PROXYSQL_BRANCH}

#
#  Build the server
#
RUN cp -r docker/images/proxysql/deb-compliant/ctl/* /root/ctl/
RUN docker/images/proxysql/deb-compliant/entrypoint/entrypoint.bash

#
#  Clean environment and run the server
#
ARG KNK_REGISTRY_URL
ARG IMAGE_TAG
FROM ${KNK_REGISTRY_URL}/pfdebian:${IMAGE_TAG}

COPY --from=build /opt/pxc_scheduler_handler/pxc_scheduler_handler /pxc_scheduler_handler
COPY --from=build /opt/proxysql/binaries/*.deb /tmp/
RUN ls -la /tmp/

ENTRYPOINT ["/bin/bash"]
